### ISSUE TITLE
RaspberryPi

### ISSUE THREAD

**Issue by rodan123** [cosinekitty/jcadmin#37]
Does not run on raspberry pi. Installed dependencies node.js and npm.
Fails syntax  for use of => in function and also use of 'of' in "var line of SplitString..."
Not portable.

**Comment by cosinekitty** [comment]
Thanks for the bug report!  Can you do this on your Pi and tell me what version you see?

```
node --version
```

**Comment by rodan123** [comment]
Thanks for looking into this, here you go.
node --version  
v0.10.29  
npm --version  
1.4.21  
uname -a  
Linux raspberrypi3 4.4.9-v7+ #884 SMP Fri May 6 17:28:59 BST 2016 armv7l GNU/Linux

**Comment by cosinekitty** [comment]
OK, that is a really old version of nodejs. You probably got that by using the raspbian wheezy package. I recommend upgrading to node 4.4.7 and npm 2.15.8 using the following procedure.  First you will probably need to uninstall the existing nodejs and npm.  Probably something like the following (not sure about the package name for nodejs).

```
sudo apt-get remove nodejs npm
```

To get the more up to date version, since you are using armv7l (thanks for providing your `uname -a` output), in your particular case you would do:

```
wget https://nodejs.org/dist/latest-v4.x/node-v4.4.7-linux-armv7l.tar.gz 
tar -xvf node*.tar.gz 
cd node*
sudo cp -R * /usr/local/
```

Anyone else who is reading this may need to replace the `armv7l` with `armv6l`, depending on your `uname -a` output.

For the sake of anyone reading this in months to come, I recommend browsing

https://nodejs.org/dist/latest-v4.x 

to find the latest version for your Raspberry Pi platform (armv6l or armv7l).

Anyway, I just tested this approach on my own Raspberry Pi and got it working:

```
don@curry ~/github/jcadmin $ uname -a
Linux curry 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l GNU/Linux
don@curry ~/github/jcadmin $ node --version
v4.4.7
don@curry ~/github/jcadmin $ npm --version
2.15.8
don@curry ~/github/jcadmin $ node jcadmin.js 8888 testdata
[2016-06-30 22:49:06.616 Thu] Loaded database from file: testdata/jcadmin.json
[2016-06-30 22:49:06.689 Thu] Monitoring jcblock path testdata
[2016-06-30 22:49:07.078 Thu] jcadmin server listening on port 8888
```

I hope this helps. Please let me know whether this works for you, or any problems you run into. I need to create a wiki to document this stuff.

**Comment by rodan123** [comment]
Thanks much, that did it, All working now. Wonder why the node.js version in the apt-get repository is so old. Thanks again for the help and for the jcadmin program.

**Comment by cosinekitty** [comment]
@rodan123 
I have started a wiki for jcadmin. I created more detailed [installation instructions](https://github.com/cosinekitty/jcadmin/wiki/Installation) that include help for Raspberry Pi users, based on your feedback and testing.

 Thanks again!  Please create more issues if you run into difficulties.  I will be writing a user guide soon too.
